version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: def-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '${PORT_NGINX}:80'
    links:
      - postgres
      - shiny
  postgres:
    image: postgres:latest
    container_name: def-postgres
    restart: always
    ports:
      - '${PORT_POSTGRES}:5432'
    expose:
      - '${PORT_POSTGRES}'
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./volumes/postgres/backups:/data:Z
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${USER_POSTGRES}"]
        interval: 30s
        timeout: 30s
        retries: 5
  shiny:
    container_name: def-shiny
    image: ${IMAGE_TAG_SHINY}
    restart: always
    user: 'root'
    ports:
      - '${PORT_SHINY}:5000'
    expose:
      - '${PORT_SHINY}'
    command: ["R", "-e", "shiny::runApp('/app/app.R', port = 5000, launch.browser=FALSE, host='0.0.0.0')"]
    volumes:
      - './volumes/shiny/shiny_logs:/var/log'
      - './.env:/app/.env'
      - './app.R:/app/app.R'
    links:
      - postgres
volumes:
  postgres: {}
  shared_database: {}
