version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: def-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '5000:80'
    links:
      - shiny
  shiny:
    container_name: def-shiny
    build: .
    user: 'root'
    ports:
      - '6543:6543'
    expose:
      - '6543'
    command: ["R", "-e", "shiny::runApp('/app/app.R', port = 6543, launch.browser=FALSE, host='0.0.0.0')"]
    volumes:
      - './volumes/shiny/shiny_logs:/var/log'
      - './.container.env:/app/.env'
      - './app.R:/app/app.R'
      - './www:/app/www'
      - './R:/app/R'
    links:
      - redis
    depends_on:
      - redis
  redis:
    container_name: 'redis'
    image: redis:6.2-alpine
    ports:
      - '6389:6379'
    expose:
      - '6389'
    command: redis-server
    volumes:
      - ./volumes/redis:/data

