# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
  api:
    links:
      - postgres
      - redis
    build: .
    command: ["/app/plumber.R"]
    command: ["R", "-e", "system('ls');"]
    volumes:
      - '.env:/app/.env'
      - './plumber.R:/app/plumber.R'
    restart: always
    ports:
      - "8000:8000"
  p
