# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    links:
      - postgres
      - redis
      - api
  api:
    links:
      - postgres
      - redis
    build: .
    command: ["/app/plumber.R"]
    # command: ["R", "-e", "system('ls');"]
    volumes:
      - '.env:/app/.env'
      - './plumber.R:/app/plumber.R'
    restart: always
    ports:
      - "8000:8000"
  postgres:
    image: postgres:12.3
    container_name: "postgres"
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./volumes/postgres/backups:/data:Z
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 30s
        timeout: 30s
        retries: 5
  redis:
    container_name: 'redis'
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server
    volumes:
      - ./volumes/redis:/data

volumes:
  postgres: {}
