# https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8321:80'
      - '443:443'
    links:
      - api
      - postgres
  api:
    build: .
    command: ["R", "-e", "source('/app/main.R')"]
    volumes:
      - '.env:/app/.env'
      - './plumber.R:/app/plumber.R'
      - './main.R:/app/main.R'
    restart: always
    ports:
      - "8000:8000"
    links:
      - postgres
  postgres:
    image: postgres:12.3
    container_name: "postgres"
    restart: always
    ports:
      - '5442:5442'
    expose:
      - '5442'
    env_file: .env
    volumes:
      - ndexpostgres:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 30s
        timeout: 30s
        retries: 5
  draw:
    image: jgraph/drawio
    ports:
      - '8080:8080'
      - '8443:8443'
volumes:
  ndexpostgres: {}
